name: Ruby

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Build and test contollers
      run: |
        gem install bundler
        bundle update fog-ovirt
        gem install ovirt-engine-sdk -v '4.3.0' --source 'https://rubygems.org/'
        sudo apt-get install libsqlite3-dev
        gem install sqlite3 -v '1.3.13' --source 'https://rubygems.org/'
        bundle install --jobs 4 --retry 3
        bundle exec rake test TEST=test/controllers/microposts_controller_test.rb
